# Sebastian Knuettel 01-12-2015
#
#last edit 08-03-2016
#
# This is code for generating 1D slices from RM images in CASA made by
# the RM code made by Dr. Eoin Murphy modified by Sebastian Knuettel
# Data is saved as .csv and a quick plot is made to visualise the slice
#
#
#
#
#
#
#

#import shutil
#import os
import numpy as np
import matplotlib.pyplot as plt
#from casa import table as tb

#Enter image stem
RM_stem = raw_input('Please enter RM image name stem >>')

blcx = input('BLC X >>')
blcy = input('BLC Y >>')
trcx = input('TRC X >>')
trcy = input('TRC Y >>')


#nuber of points for slice, for interpolation
N_PTS = 250 


#single line slice
ia.open(RM_stem+'_RM.im')#code assumes RMmap and error map have file endings
#_RM.im and _eRM.im respectively, as generated by the RM code

rec = ia.getslice( x=[blcx,trcx],y=[blcy,trcy],npts=N_PTS,method = 'linear' )
RM_vals = rec['pixel']
D_vals = rec['distance']
ia.close()

ia.open(RM_stem+'_eRM.im')
rec = ia.getslice( x=[blcx,trcx],y=[blcy,trcy],npts=N_PTS,method = 'linear' )
RM_err_vals = rec['pixel']
ia.close()


#get cellsize from image header in radians
cellsize = (imhead(imagename=RM_stem+'_RM.im',mode='get',hdkey='cdelt2'))['value']

cellsize = abs(cellsize)
cellsize = cellsize*206264.8062 #converts to arcsec

D_vals =  np.multiply(D_vals,cellsize) #converts pixel distance to arcsec



outslice = np.column_stack((D_vals,RM_vals,RM_err_vals)) #creates 2d array for output


print 'Slice read successfully!!!\n\n'

outname = raw_input('Please input name stem for slice file >>')

np.savetxt(outname+'.csv', outslice, fmt = '%1.4e', delimiter = ',',header= 'Distance(arcsec),RM(rad/m/m),RMerr(rad/m/m)')

#calculates significance of slice
sigma = np.abs(RM_vals[0] - RM_vals[-1])
sigma = sigma/(np.sqrt(RM_err_vals[0]*RM_err_vals[0] + RM_err_vals[-1]*RM_err_vals[-1]))
sigma = round(sigma,1)

plt.figure(figsize=(10,6))
plt.plot(D_vals, RM_vals, 'k-', linewidth = 3) #plots slice
plt.fill_between(D_vals, RM_vals-RM_err_vals, RM_vals+RM_err_vals, facecolor ='gray') #plots error bars
#the following changes font sizes for the labels
plt.xlabel('Transverse Slice (arcsec)', fontsize=20)
plt.xlim(xmin=-cellsize,xmax=RM_vals[-1]+cellsize)
plt.xticks(fontsize = 16)
plt.yticks(fontsize = 16)
plt.ylabel('Rotation Measure (rad m$^{-2}$)',fontsize=20)
plt.title(r'Significance  %.1f$\sigma$' % sigma, fontsize=18, ) #Notice the r before the string

print 'Done!!!\n'



